name: CI Pipeline

on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          pip install uv

      - name: Create Virtual Environment
        run: |
          uv venv

      - name: Install dependencies using uv
        run: |
          uv pip install -e .

      - name: Run mypy
        run: |
          uv run mypy --namespace-packages --explicit-package-bases .

      - name: Run ruff
        run: |
          uv run ruff check .

      - name: Run Bandit
        run: |
          uv run bandit -r . -c pyproject.toml

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{secrets.GCP_SA_KEY}}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}

      # - name: Run Tests
      #   env:
      #     API_FOOTBALL_KEY: "dummy_key"
      #     GOOGLE_MAPS_API_KEY: "dummy_key"
      #     GCP_PROJECT_ID: "dummy_id"
      #     REDDIT_CLIENT_ID: "dummy_id"
      #     REDDIT_CLIENT_SECRET: "dummy_key"

      #   run: |
      #     export PYTHONPATH=$PYTHONPATH:$(pwd)
      #     uv run pytest tests/
