name: CI Pipeline

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          pip install uv

      - name: Create Virtual Environment
        run: |
          uv venv

      - name: Install dependencies using uv
        run: |
          uv pip install -e .

      # - name: Run mypy
      #   run: |
      #     uv run mypy --namespace-packages --explicit-package-bases .

      # - name: Run ruff
      #   run: |
      #     uv run ruff check .

      # - name: Run Bandit
      #   run: |
      #     uv run bandit -r . -c pyproject.toml

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{secrets.GCP_SA_KEY}}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}

      # - name: Run Tests
      #   env:
      #     API_FOOTBALL_KEY: "dummy_key"
      #     GOOGLE_MAPS_API_KEY: "dummy_key"
      #     GCP_PROJECT_ID: "dummy_id"
      #     REDDIT_CLIENT_ID: "dummy_id"
      #     REDDIT_CLIENT_SECRET: "dummy_key"

      #   run: |
      #     export PYTHONPATH=$PYTHONPATH:$(pwd)
      #     uv run pytest tests/

      # - name: Create Pub/Sub Topics
      #   run: |
      #     uv run gcloud pubsub topics create fetch_league_data_topic || true
      #     uv run gcloud pubsub topics create fetch_reddit_data_topic || true
      #     uv run gcloud pubsub topics create fetch_football_data_topic || true
      #     uv run gcloud pubsub topics create fetch_weather_data_topic || true
      #     uv run gcloud pubsub topics create convert_to_parquet_topic || true
      #     uv run gcloud pubsub topics create convert_weather_to_parquet_topic || true
      #     uv run gcloud pubsub topics create match_to_bigquery_topic || true
      #     uv run gcloud pubsub topics create weather_to_bigquery_topic || true
      #     uv run gcloud pubsub topics create transform_matches_topic || true
      #     uv run gcloud pubsub topics create transform_weather_topic || true
      #     uv run gcloud pubsub topics create fetch_standings_data_topic || true
      #     uv run gcloud pubsub topics create convert_standings_to_parquet_topic || true
      #     uv run gcloud pubsub topics create convert_standings_to_parquet_topic || true
      #     uv run gcloud pubsub topics create standings_to_bigquery_topic || true
      #     uv run gcloud pubsub topics create transform_standings_topic || true
      #     uv run gcloud pubsub topics create convert_reddit_to_parquet_topic || true
      #     uv run gcloud pubsub topics create reddit_to_bigquery_topic || true
      #     uv run gcloud pubsub topics create process_reddit_data_topic || true
      #     uv run gcloud pubsub topics create transform_reddit_topic || true
      #     uv run gcloud pubsub topics create trigger_quality_scans_topic || true

      - name: Deploy Data Validation Function
        run: |
          cd cloud_functions/data_validation
          uv run gcloud functions deploy trigger_dataplex_scans_test \
            --runtime python312 \
            --trigger-topic trigger_quality_scans_topic \
            --entry-point trigger_dataplex_scans \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy fetch_league_data Function
        run: |
          cd cloud_functions/league_data/fetch_league_data_function
          uv run gcloud functions deploy fetch_league_data \
            --runtime python312 \
            --trigger-topic fetch_league_data_topic \
            --entry-point fetch_league_data \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "API_FOOTBALL_KEY=${{secrets.API_FOOTBALL_KEY}},DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},GOOGLE_MAPS_API_KEY=${{secrets.GOOGLE_MAPS_API_KEY}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy fetch_football_data Function
        run: |
          cd cloud_functions/match_data/fetch_match_data_function
          uv run gcloud functions deploy fetch_football_data \
            --runtime python312 \
            --trigger-topic fetch_football_data_topic \
            --entry-point fetch_football_data \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "API_FOOTBALL_KEY=${{secrets.API_FOOTBALL_KEY}},DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}},BUCKET_NAME=${{secrets.BUCKET_NAME}}"
          cd ../..

      - name: Deploy fetch_weather_data Function
        run: |
          cd cloud_functions/weather_data/fetch_weather_data_function
          uv run gcloud functions deploy fetch_weather_data \
            --runtime python312 \
            --trigger-topic fetch_weather_data_topic \
            --entry-point fetch_weather_data \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},BUCKET_NAME=${{secrets.BUCKET_NAME}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy convert_match_data Function
        run: |
          cd cloud_functions/match_data/convert_match_data_function
          uv run gcloud functions deploy transform_match_to_parquet \
            --runtime python312 \
            --trigger-topic convert_to_parquet_topic \
            --entry-point transform_to_parquet \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},BUCKET_NAME=${{secrets.BUCKET_NAME}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy convert_weather_data Function
        run: |
          cd cloud_functions/weather_data/convert_weather_data_function
          uv run gcloud functions deploy transform_weather_to_parquet \
            --runtime python312 \
            --trigger-topic convert_weather_to_parquet_topic \
            --entry-point transform_to_parquet \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},BUCKET_NAME=${{secrets.BUCKET_NAME}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy match_to_bigquery Function
        run: |
          cd cloud_functions/match_data/match_to_bigquery_function
          uv run gcloud functions deploy load_matches_to_bigquery \
            --runtime python312 \
            --trigger-topic match_to_bigquery_topic \
            --entry-point load_matches_to_bigquery \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},BUCKET_NAME=${{secrets.BUCKET_NAME}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy weather_to_bigquery Function
        run: |
          cd cloud_functions/weather_data/weather_to_bigquery_function
          uv run gcloud functions deploy load_weather_to_bigquery \
            --runtime python312 \
            --trigger-topic weather_to_bigquery_topic \
            --entry-point load_weather_to_bigquery \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},BUCKET_NAME=${{secrets.BUCKET_NAME}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy match_transform Function
        run: |
          cd cloud_functions/match_data/match_transform_function
          uv run gcloud functions deploy transform_matches \
            --runtime python312 \
            --trigger-topic transform_matches_topic \
            --entry-point transform_matches \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}},DATAFORM_REPOSITORY=${{secrets.DATAFORM_REPOSITORY}},DATAFORM_WORKSPACE=${{secrets.DATAFORM_WORKSPACE}}"
          cd ../..

      - name: Deploy weather_transform Function
        run: |
          cd cloud_functions/weather_data/weather_transform_function
          uv run gcloud functions deploy transform_weather \
            --runtime python312 \
            --trigger-topic transform_weather_topic \
            --entry-point transform_weather \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}},DATAFORM_REPOSITORY=${{secrets.DATAFORM_REPOSITORY}},DATAFORM_WORKSPACE=${{secrets.DATAFORM_WORKSPACE}}"
          cd ../..

      - name: Deploy fetch_standings_data Function
        run: |
          cd cloud_functions/standings_data/fetch_standings_data_function
          uv run gcloud functions deploy fetch_standings_data \
          --runtime python312 \
          --trigger-topic fetch_standings_data_topic \
          --entry-point fetch_standings_data \
          --timeout 540s \
          --memory 1GiB \
          --region europe-central2 \
          --set-env-vars "API_FOOTBALL_KEY=${{secrets.API_FOOTBALL_KEY}},DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}},BUCKET_NAME=${{secrets.BUCKET_NAME}}"
          cd ../..

      - name: Deploy convert_standings_data Function
        run: |
          cd cloud_functions/standings_data/convert_standings_data_function
          uv run gcloud functions deploy transform_standings_to_parquet \
          --runtime python312 \
          --trigger-topic convert_standings_to_parquet_topic \
          --entry-point transform_to_parquet \
          --timeout 540s \
          --memory 1GiB \
          --region europe-central2 \
          --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},BUCKET_NAME=${{secrets.BUCKET_NAME}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy standings_to_bigquery Function
        run: |
          cd cloud_functions/standings_data/standings_to_bigquery_function
          uv run gcloud functions deploy load_standings_to_bigquery \
            --runtime python312 \
            --trigger-topic standings_to_bigquery_topic \
            --entry-point load_standings_to_bigquery \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }},BUCKET_NAME=${{ secrets.BUCKET_NAME }},GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
          cd ../..

      - name: Deploy standings_transform Function
        run: |
          cd cloud_functions/standings_data/standings_transform_function
          uv run gcloud functions deploy transform_standings \
          --runtime python312 \
          --trigger-topic transform_standings_topic \
          --entry-point transform_standings \
          --timeout 540s \
          --memory 1GiB \
          --region europe-central2 \
          --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}},DATAFORM_REPOSITORY=${{secrets.DATAFORM_REPOSITORY}},DATAFORM_WORKSPACE=${{secrets.DATAFORM_WORKSPACE}}"
          cd ../..

      - name: Deploy fetch_reddit_data Function
        run: |
          cd cloud_functions/reddit_data/fetch_reddit_data_function
          uv run gcloud functions deploy fetch_reddit_data \
          --runtime python312 \
          --trigger-topic fetch_reddit_data_topic \
          --entry-point fetch_reddit_data \
          --timeout 540s \
          --memory 1GiB \
          --region europe-central2 \
          --set-env-vars "REDDIT_CLIENT_ID=${{secrets.REDDIT_CLIENT_ID}},REDDIT_CLIENT_SECRET=${{secrets.REDDIT_CLIENT_SECRET}},DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},BUCKET_NAME=${{secrets.BUCKET_NAME}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy convert_reddit_data Function
        run: |
          cd cloud_functions/reddit_data/convert_reddit_data_function
          uv run gcloud functions deploy transform_reddit_to_parquet \
            --runtime python312 \
            --trigger-topic convert_reddit_to_parquet_topic \
            --entry-point transform_to_parquet \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},BUCKET_NAME=${{secrets.BUCKET_NAME}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy reddit_to_bigquery Function
        run: |
          cd cloud_functions/reddit_data/reddit_to_bigquery_function
          uv run gcloud functions deploy load_reddit_to_bigquery \
            --runtime python312 \
            --trigger-topic reddit_to_bigquery_topic \
            --entry-point load_reddit_to_bigquery \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},BUCKET_NAME=${{secrets.BUCKET_NAME}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy process_reddit_data Function
        run: |
          cd cloud_functions/reddit_data/process_reddit_data_function
          uv run gcloud functions deploy process_reddit_data \
            --runtime python312 \
            --trigger-topic process_reddit_data_topic \
            --entry-point process_reddit_threads \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},BUCKET_NAME=${{secrets.BUCKET_NAME}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}}"
          cd ../..

      - name: Deploy reddit_transform Function
        run: |
          cd cloud_functions/reddit_data/reddit_transform_function
          uv run gcloud functions deploy transform_reddit \
            --runtime python312 \
            --trigger-topic transform_reddit_topic \
            --entry-point transform_reddit \
            --timeout 540s \
            --memory 1GiB \
            --region europe-central2 \
            --set-env-vars "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}},GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}},DATAFORM_REPOSITORY=${{secrets.DATAFORM_REPOSITORY}},DATAFORM_WORKSPACE=${{secrets.DATAFORM_WORKSPACE}}"
          cd ../..
